# Generated by Django 4.2.13 on 2024-06-20 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('fabric', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
                ('four_way_stretch', models.BooleanField()),
                ('price', models.IntegerField()),
            ],
        ),
    ]
